var BabelFrog = BabelFrog || {};

BabelFrog.getLingueeUrl = function(fromCode, toCode, query) {
  var languagePairUrl = {
    'en-de': 'http://www.linguee.com/english-german',
    'en-fr': 'http://www.linguee.com/english-french',
    'en-es': 'http://www.linguee.com/english-spanish',
    'en-pt': 'http://www.linguee.com/english-portuguese',
    'en-it': 'http://www.linguee.com/english-italian',
    'en-ru': 'http://www.linguee.com/english-russian',
    'en-ja': 'http://www.linguee.com/english-japanese',
    'en-zh': 'http://www.linguee.com/english-chinese',
    'en-pl': 'http://www.linguee.com/english-polish',
    'en-nl': 'http://www.linguee.com/english-dutch',
    'en-sv': 'http://www.linguee.com/english-swedish',
    'en-da': 'http://www.linguee.com/english-danish',
    'en-fi': 'http://www.linguee.com/english-finnish',
    'en-el': 'http://www.linguee.com/english-greek',
    'en-cs': 'http://www.linguee.com/english-czech',
    'en-ro': 'http://www.linguee.com/english-romanian',
    'en-hu': 'http://www.linguee.com/english-hungarian',
    'en-sk': 'http://www.linguee.com/english-slovak',
    'en-bg': 'http://www.bg.linguee.com/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'en-sl': 'http://www.linguee.com/english-slovene',
    'en-lt': 'http://www.linguee.com/english-lithuanian',
    'en-lv': 'http://www.linguee.com/english-latvian',
    'en-et': 'http://www.linguee.com/english-estonian',
    'en-mt': 'http://www.linguee.com/english-maltese',
    'de-en': 'http://www.linguee.de/deutsch-englisch',
    'de-fr': 'http://www.linguee.de/deutsch-franzoesisch',
    'de-es': 'http://www.linguee.de/deutsch-spanisch',
    'de-pt': 'http://www.linguee.de/deutsch-portugiesisch',
    'de-it': 'http://www.linguee.de/deutsch-italienisch',
    'de-nl': 'http://www.linguee.de/deutsch-niederl%C3%A4ndisch',
    'de-pl': 'http://www.linguee.de/deutsch-polnisch',
    'de-sv': 'http://www.linguee.de/deutsch-schwedisch',
    'de-da': 'http://www.linguee.de/deutsch-d%C3%A4nisch',
    'de-fi': 'http://www.linguee.de/deutsch-finnisch',
    'de-el': 'http://www.linguee.de/deutsch-griechisch',
    'de-cs': 'http://www.linguee.de/deutsch-tschechisch',
    'de-ro': 'http://www.linguee.de/deutsch-rum%C3%A4nisch',
    'de-hu': 'http://www.linguee.de/deutsch-ungarisch',
    'de-sk': 'http://www.linguee.de/deutsch-slowakisch',
    'de-bg': 'http://www.bg.linguee.com/%D0%BD%D0%B5%D0%BC%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'de-sl': 'http://www.linguee.de/deutsch-slowenisch',
    'de-lt': 'http://www.linguee.de/deutsch-litauisch',
    'de-lv': 'http://www.linguee.de/deutsch-lettisch',
    'de-et': 'http://www.linguee.de/deutsch-estnisch',
    'de-mt': 'http://www.linguee.de/deutsch-maltesisch',
    'fr-en': 'http://www.linguee.fr/francais-anglais',
    'fr-de': 'http://www.linguee.fr/francais-allemand',
    'fr-es': 'http://www.linguee.fr/francais-espagnol',
    'fr-pt': 'http://www.linguee.fr/francais-portugais',
    'fr-it': 'http://www.linguee.fr/francais-italien',
    'fr-nl': 'http://www.linguee.fr/francais-neerlandais',
    'fr-pl': 'http://www.linguee.fr/francais-polonais',
    'fr-sv': 'http://www.linguee.fr/francais-suedois',
    'fr-da': 'http://www.linguee.fr/francais-danois',
    'fr-fi': 'http://www.linguee.fr/francais-finnois',
    'fr-el': 'http://www.linguee.fr/francais-grec',
    'fr-cs': 'http://www.linguee.fr/francais-tcheque',
    'fr-ro': 'http://www.linguee.fr/francais-roumain',
    'fr-hu': 'http://www.linguee.fr/francais-hongrois',
    'fr-sk': 'http://www.linguee.fr/francais-slovaque',
    'fr-bg': 'http://www.bg.linguee.com/%D1%84%D1%80%D0%B5%D0%BD%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'fr-sl': 'http://www.linguee.fr/francais-slovene',
    'fr-lt': 'http://www.linguee.fr/francais-lituanien',
    'fr-lv': 'http://www.linguee.fr/francais-letton',
    'fr-et': 'http://www.linguee.fr/francais-estonien',
    'fr-mt': 'http://www.linguee.fr/francais-maltais',
    'es-en': 'http://www.linguee.es/espanol-ingles',
    'es-de': 'http://www.linguee.es/espanol-aleman',
    'es-fr': 'http://www.linguee.es/espanol-frances',
    'es-pt': 'http://www.linguee.es/espanol-portugues',
    'es-it': 'http://www.linguee.es/espanol-italiano',
    'es-nl': 'http://www.linguee.es/espanol-neerlandes',
    'es-pl': 'http://www.linguee.es/espanol-polaco',
    'es-sv': 'http://www.linguee.es/espanol-sueco',
    'es-da': 'http://www.linguee.es/espanol-danes',
    'es-fi': 'http://www.linguee.es/espanol-fines',
    'es-el': 'http://www.linguee.es/espanol-griego',
    'es-cs': 'http://www.linguee.es/espanol-checo',
    'es-ro': 'http://www.linguee.es/espanol-rumano',
    'es-hu': 'http://www.linguee.es/espanol-hungaro',
    'es-sk': 'http://www.linguee.es/espanol-eslovaco',
    'es-bg': 'http://www.bg.linguee.com/%D0%B8%D1%81%D0%BF%D0%B0%D0%BD%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'es-sl': 'http://www.linguee.es/espanol-esloveno',
    'es-lt': 'http://www.linguee.es/espanol-lituano',
    'es-lv': 'http://www.linguee.es/espanol-leton',
    'es-et': 'http://www.linguee.es/espanol-estonio',
    'es-mt': 'http://www.linguee.es/espanol-maltes',
    'zh-en': 'http://www.cn.linguee.com/%E4%B8%AD%E6%96%87-%E8%8B%B1%E8%AF%AD',
    'ru-en': 'http://www.linguee.ru/%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9-%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9',
    'ja-en': 'http://www.linguee.jp/%E6%97%A5%E6%9C%AC%E8%AA%9E-%E8%8B%B1%E8%AA%9E',
    'pt-en': 'http://www.linguee.pt/portugues-ingles',
    'pt-de': 'http://www.linguee.pt/portugues-alemao',
    'pt-fr': 'http://www.linguee.pt/portugues-frances',
    'pt-es': 'http://www.linguee.pt/portugues-espanhol',
    'pt-it': 'http://www.linguee.pt/portugues-italiano',
    'pt-nl': 'http://www.linguee.pt/portugues-holandes',
    'pt-pl': 'http://www.linguee.pt/portugues-polones',
    'pt-sv': 'http://www.linguee.pt/portugues-sueco',
    'pt-da': 'http://www.linguee.pt/portugues-dinamarques',
    'pt-fi': 'http://www.linguee.pt/portugues-finlandes',
    'pt-el': 'http://www.linguee.pt/portugues-grego',
    'pt-cs': 'http://www.linguee.pt/portugues-checo',
    'pt-ro': 'http://www.linguee.pt/portugues-romeno',
    'pt-hu': 'http://www.linguee.pt/portugues-hungaro',
    'pt-sk': 'http://www.linguee.pt/portugues-eslovaco',
    'pt-bg': 'http://www.bg.linguee.com/%D0%BF%D0%BE%D1%80%D1%82%D1%83%D0%B3%D0%B0%D0%BB%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'pt-sl': 'http://www.linguee.pt/portugues-esloveno',
    'pt-lt': 'http://www.linguee.pt/portugues-lituano',
    'pt-lv': 'http://www.linguee.pt/portugues-letao',
    'pt-et': 'http://www.linguee.pt/portugues-estonio',
    'pt-mt': 'http://www.linguee.pt/portugues-maltes',
    'it-en': 'http://www.linguee.it/italiano-inglese',
    'it-de': 'http://www.linguee.it/italiano-tedesco',
    'it-fr': 'http://www.linguee.it/italiano-francese',
    'it-es': 'http://www.linguee.it/italiano-spagnolo',
    'it-pt': 'http://www.linguee.it/italiano-portoghese',
    'it-nl': 'http://www.linguee.it/italiano-olandese',
    'it-pl': 'http://www.linguee.it/italiano-polacco',
    'it-sv': 'http://www.linguee.it/italiano-svedese',
    'it-da': 'http://www.linguee.it/italiano-danese',
    'it-fi': 'http://www.linguee.it/italiano-finlandese',
    'it-el': 'http://www.linguee.it/italiano-greco',
    'it-cs': 'http://www.linguee.it/italiano-ceco',
    'it-ro': 'http://www.linguee.it/italiano-rumeno',
    'it-hu': 'http://www.linguee.it/italiano-ungherese',
    'it-sk': 'http://www.linguee.it/italiano-slovacco',
    'it-bg': 'http://www.bg.linguee.com/%D0%B8%D1%82%D0%B0%D0%BB%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'it-sl': 'http://www.linguee.it/italiano-sloveno',
    'it-lt': 'http://www.linguee.it/italiano-lituano',
    'it-lv': 'http://www.linguee.it/italiano-lettone',
    'it-et': 'http://www.linguee.it/italiano-estone',
    'it-mt': 'http://www.linguee.it/italiano-maltese',
    'nl-en': 'http://www.linguee.nl/nederlands-engels',
    'nl-de': 'http://www.linguee.nl/nederlands-duits',
    'nl-fr': 'http://www.linguee.nl/nederlands-frans',
    'nl-es': 'http://www.linguee.nl/nederlands-spaans',
    'nl-pt': 'http://www.linguee.nl/nederlands-portugees',
    'nl-it': 'http://www.linguee.nl/nederlands-italiaans',
    'nl-pl': 'http://www.linguee.nl/nederlands-pools',
    'nl-sv': 'http://www.linguee.nl/nederlands-zweeds',
    'nl-da': 'http://www.linguee.nl/nederlands-deens',
    'nl-fi': 'http://www.linguee.nl/nederlands-fins',
    'nl-el': 'http://www.linguee.nl/nederlands-grieks',
    'nl-cs': 'http://www.linguee.nl/nederlands-tsjechisch',
    'nl-ro': 'http://www.linguee.nl/nederlands-roemeens',
    'nl-hu': 'http://www.linguee.nl/nederlands-hongaars',
    'nl-sk': 'http://www.linguee.nl/nederlands-slowaaks',
    'nl-bg': 'http://www.bg.linguee.com/%D1%85%D0%BE%D0%BB%D0%B0%D0%BD%D0%B4%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'nl-sl': 'http://www.linguee.nl/nederlands-sloveens',
    'nl-lt': 'http://www.linguee.nl/nederlands-litouws',
    'nl-lv': 'http://www.linguee.nl/nederlands-lets',
    'nl-et': 'http://www.linguee.nl/nederlands-ests',
    'nl-mt': 'http://www.linguee.nl/nederlands-maltees',
    'pl-en': 'http://www.linguee.pl/polski-angielski',
    'pl-de': 'http://www.linguee.pl/polski-niemiecki',
    'pl-fr': 'http://www.linguee.pl/polski-francuski',
    'pl-es': 'http://www.linguee.pl/polski-hiszpa%C5%84ski',
    'pl-pt': 'http://www.linguee.pl/polski-portugalski',
    'pl-it': 'http://www.linguee.pl/polski-w%C5%82oski',
    'pl-nl': 'http://www.linguee.pl/polski-holenderski',
    'pl-sv': 'http://www.linguee.pl/polski-szwedzki',
    'pl-da': 'http://www.linguee.pl/polski-du%C5%84ski',
    'pl-fi': 'http://www.linguee.pl/polski-fi%C5%84ski',
    'pl-el': 'http://www.linguee.pl/polski-grecki',
    'pl-cs': 'http://www.linguee.pl/polski-czeski',
    'pl-ro': 'http://www.linguee.pl/polski-rumu%C5%84ski',
    'pl-hu': 'http://www.linguee.pl/polski-w%C4%99gierski',
    'pl-sk': 'http://www.linguee.pl/polski-s%C5%82owacki',
    'pl-bg': 'http://www.bg.linguee.com/%D0%BB%D0%B0%D0%BA-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'pl-sl': 'http://www.linguee.pl/polski-s%C5%82owe%C5%84ski',
    'pl-lt': 'http://www.linguee.pl/polski-litewski',
    'pl-lv': 'http://www.linguee.pl/polski-%C5%82otewski',
    'pl-et': 'http://www.linguee.pl/polski-esto%C5%84ski',
    'pl-mt': 'http://www.linguee.pl/polski-malta%C5%84ski',
    'sv-en': 'http://www.linguee.se/svensk-engelsk',
    'sv-de': 'http://www.linguee.se/svensk-tysk',
    'sv-fr': 'http://www.linguee.se/svensk-fransk',
    'sv-es': 'http://www.linguee.se/svensk-spansk',
    'sv-pt': 'http://www.linguee.se/svensk-portugisisk',
    'sv-it': 'http://www.linguee.se/svensk-italiensk',
    'sv-nl': 'http://www.linguee.se/svensk-holl%C3%A4ndsk',
    'sv-pl': 'http://www.linguee.se/svensk-polsk',
    'sv-da': 'http://www.linguee.se/svensk-dansk',
    'sv-fi': 'http://www.linguee.se/svensk-finsk',
    'sv-el': 'http://www.linguee.se/svensk-grekisk',
    'sv-cs': 'http://www.linguee.se/svensk-tjeckisk',
    'sv-ro': 'http://www.linguee.se/svensk-rum%C3%A4nsk',
    'sv-hu': 'http://www.linguee.se/svensk-ungersk',
    'sv-sk': 'http://www.linguee.se/svensk-slovakisk',
    'sv-bg': 'http://www.bg.linguee.com/%D1%88%D0%B2%D0%B5%D0%B4%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'sv-sl': 'http://www.linguee.se/svensk-slovensk',
    'sv-lt': 'http://www.linguee.se/svensk-litauisk',
    'sv-lv': 'http://www.linguee.se/svensk-lettisk',
    'sv-et': 'http://www.linguee.se/svensk-estnisk',
    'sv-mt': 'http://www.linguee.se/svensk-maltesisk',
    'da-en': 'http://www.linguee.dk/dansk-engelsk',
    'da-de': 'http://www.linguee.dk/dansk-tysk',
    'da-fr': 'http://www.linguee.dk/dansk-fransk',
    'da-es': 'http://www.linguee.dk/dansk-spansk',
    'da-pt': 'http://www.linguee.dk/dansk-portugisisk',
    'da-it': 'http://www.linguee.dk/dansk-italiensk',
    'da-nl': 'http://www.linguee.dk/dansk-hollandsk',
    'da-pl': 'http://www.linguee.dk/dansk-polik',
    'da-sv': 'http://www.linguee.dk/dansk-svensk',
    'da-fi': 'http://www.linguee.dk/dansk-finsk',
    'da-el': 'http://www.linguee.dk/dansk-gr%C3%A6sk',
    'da-cs': 'http://www.linguee.dk/dansk-tjekkisk',
    'da-ro': 'http://www.linguee.dk/dansk-rum%C3%A6nsk',
    'da-hu': 'http://www.linguee.dk/dansk-ungarsk',
    'da-sk': 'http://www.linguee.dk/dansk-slovakisk',
    'da-bg': 'http://www.bg.linguee.com/%D0%B4%D0%B0%D1%82%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'da-sl': 'http://www.linguee.dk/dansk-slovensk',
    'da-lt': 'http://www.linguee.dk/dansk-litauisk',
    'da-lv': 'http://www.linguee.dk/dansk-letlandsk',
    'da-et': 'http://www.linguee.dk/dansk-estisk',
    'da-mt': 'http://www.linguee.dk/dansk-maltesisk',
    'fi-en': 'http://www.fi.linguee.com/suomi-englanti',
    'fi-de': 'http://www.fi.linguee.com/suomi-saksa',
    'fi-fr': 'http://www.fi.linguee.com/suomi-ranska',
    'fi-es': 'http://www.fi.linguee.com/suomi-espanja',
    'fi-pt': 'http://www.fi.linguee.com/suomi-portugali',
    'fi-it': 'http://www.fi.linguee.com/suomi-italia',
    'fi-nl': 'http://www.fi.linguee.com/suomi-hollanti',
    'fi-pl': 'http://www.fi.linguee.com/suomi-puola',
    'fi-sv': 'http://www.fi.linguee.com/suomi-ruotsi',
    'fi-da': 'http://www.fi.linguee.com/suomi-tanska',
    'fi-el': 'http://www.fi.linguee.com/suomi-kreikka',
    'fi-cs': 'http://www.fi.linguee.com/suomi-t%C5%A1ekki',
    'fi-ro': 'http://www.fi.linguee.com/suomi-romania',
    'fi-hu': 'http://www.fi.linguee.com/suomi-unkari',
    'fi-sk': 'http://www.fi.linguee.com/suomi-slovakki',
    'fi-bg': 'http://www.bg.linguee.com/%D1%84%D0%B8%D0%BD%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'fi-sl': 'http://www.fi.linguee.com/suomi-slovenia',
    'fi-lt': 'http://www.fi.linguee.com/suomi-liettua',
    'fi-lv': 'http://www.fi.linguee.com/suomi-latvia',
    'fi-et': 'http://www.fi.linguee.com/suomi-viro',
    'fi-mt': 'http://www.fi.linguee.com/suomi-malta',
    'el-en': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B1%CE%B3%CE%B3%CE%BB%CE%B9%CE%BA%CE%AC',
    'el-de': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B3%CE%B5%CF%81%CE%BC%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-fr': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B3%CE%B1%CE%BB%CE%BB%CE%B9%CE%BA%CE%AC',
    'el-es': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B9%CF%83%CF%80%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-pt': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%80%CE%BF%CF%81%CF%84%CE%BF%CE%B3%CE%B1%CE%BB%CE%B9%CE%BA%CE%AC',
    'el-it': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B9%CF%84%CE%B1%CE%BB%CE%B9%CE%BA%CE%AC',
    'el-nl': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BF%CE%BB%CE%BB%CE%B1%CE%BD%CE%B4%CE%B9%CE%BA%CE%AC',
    'el-pl': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%80%CE%BF%CE%BB%CF%89%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-sv': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%83%CE%BF%CF%85%CE%B7%CE%B4%CE%B9%CE%BA%CE%AC',
    'el-da': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B4%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-fi': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%86%CE%B9%CE%BD%CE%BB%CE%B1%CE%BD%CE%B4%CE%B9%CE%BA%CE%AC',
    'el-cs': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%84%CF%83%CE%B5%CF%87%CE%B9%CE%BA%CE%AC',
    'el-ro': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%81%CE%BF%CF%85%CE%BC%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-hu': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BF%CF%85%CE%B3%CE%B3%CF%81%CE%B9%CE%BA%CE%AC',
    'el-sk': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%83%CE%BB%CE%BF%CE%B2%CE%AC%CE%BA%CE%B9%CE%BA%CE%B1',
    'el-bg': 'http://www.bg.linguee.com/%D0%B3%D1%80%D1%8A%D1%86%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'el-sl': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%83%CE%BB%CE%BF%CE%B2%CE%AD%CE%BD%CE%B9%CE%BA%CE%B1',
    'el-lt': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BB%CE%B9%CE%B8%CE%BF%CF%85%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-lv': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BB%CE%B5%CF%84%CE%BF%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-et': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B5%CF%83%CE%B8%CE%BF%CE%BD%CE%B9%CE%BA%CE%AC',
    'el-mt': 'http://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BC%CE%B1%CE%BB%CF%84%CE%AD%CE%B6%CE%B9%CE%BA%CE%B1',
    'cs-en': 'http://www.linguee.cz/%C4%8De%C5%A1tina-angli%C4%8Dtina',
    'cs-de': 'http://www.linguee.cz/%C4%8De%C5%A1tina-n%C4%9Bm%C4%8Dina',
    'cs-fr': 'http://www.linguee.cz/%C4%8De%C5%A1tina-francouz%C5%A1tina',
    'cs-es': 'http://www.linguee.cz/%C4%8De%C5%A1tina-%C5%A1pan%C4%9Bl%C5%A1tina',
    'cs-pt': 'http://www.linguee.cz/%C4%8De%C5%A1tina-portugal%C5%A1tina',
    'cs-it': 'http://www.linguee.cz/%C4%8De%C5%A1tina-ital%C5%A1tina',
    'cs-nl': 'http://www.linguee.cz/%C4%8De%C5%A1tina-holand%C5%A1tina',
    'cs-pl': 'http://www.linguee.cz/%C4%8De%C5%A1tina-pol%C5%A1tina',
    'cs-sv': 'http://www.linguee.cz/%C4%8De%C5%A1tina-%C5%A1v%C3%A9d%C5%A1tina',
    'cs-da': 'http://www.linguee.cz/%C4%8De%C5%A1tina-d%C3%A1n%C5%A1tina',
    'cs-fi': 'http://www.linguee.cz/%C4%8De%C5%A1tina-fin%C5%A1tina',
    'cs-el': 'http://www.linguee.cz/%C4%8De%C5%A1tina-%C5%99e%C4%8Dtina',
    'cs-ro': 'http://www.linguee.cz/%C4%8De%C5%A1tina-rumun%C5%A1tina',
    'cs-hu': 'http://www.linguee.cz/%C4%8De%C5%A1tina-ma%C4%8Far%C5%A1tina',
    'cs-sk': 'http://www.linguee.cz/%C4%8De%C5%A1tina-sloven%C5%A1tina',
    'cs-bg': 'http://www.bg.linguee.com/%D1%87%D0%B5%D1%88%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'cs-sl': 'http://www.linguee.cz/%C4%8De%C5%A1tina-slovin%C5%A1tina',
    'cs-lt': 'http://www.linguee.cz/%C4%8De%C5%A1tina-litev%C5%A1tina',
    'cs-lv': 'http://www.linguee.cz/%C4%8De%C5%A1tina-loty%C5%A1tina',
    'cs-et': 'http://www.linguee.cz/%C4%8De%C5%A1tina-eston%C5%A1tina',
    'cs-mt': 'http://www.linguee.cz/%C4%8De%C5%A1tina-malt%C5%A1tina',
    'ro-en': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-englez%C4%83',
    'ro-de': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-german%C4%83',
    'ro-fr': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-francez%C4%83',
    'ro-es': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-spaniol%C4%83',
    'ro-pt': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-portughez%C4%83',
    'ro-it': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-italian%C4%83',
    'ro-nl': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-olandez%C4%83',
    'ro-pl': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-polonez%C4%83',
    'ro-sv': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-suedez%C4%83',
    'ro-da': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-danez%C4%83',
    'ro-fi': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-finlandez%C4%83',
    'ro-el': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-greac%C4%83',
    'ro-cs': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-ceh%C4%83',
    'ro-hu': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-maghiar%C4%83',
    'ro-sk': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-slovac%C4%83',
    'ro-bg': 'http://www.bg.linguee.com/%D1%80%D1%83%D0%BC%D1%8A%D0%BD%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'ro-sl': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-sloven%C4%83',
    'ro-lt': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-lituanian%C4%83',
    'ro-lv': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-leton%C4%83',
    'ro-et': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-eston%C4%83',
    'ro-mt': 'http://www.ro.linguee.com/rom%C3%A2n%C4%83-maltez%C4%83',
    'hu-en': 'http://www.linguee.hu/magyar-angol',
    'hu-de': 'http://www.linguee.hu/magyar-n%C3%A9met',
    'hu-fr': 'http://www.linguee.hu/magyar-francia',
    'hu-es': 'http://www.linguee.hu/magyar-spanyol',
    'hu-pt': 'http://www.linguee.hu/magyar-portug%C3%A1l',
    'hu-it': 'http://www.linguee.hu/magyar-olasz',
    'hu-nl': 'http://www.linguee.hu/magyar-holland',
    'hu-pl': 'http://www.linguee.hu/magyar-lengyel',
    'hu-sv': 'http://www.linguee.hu/magyar-sv%C3%A9d',
    'hu-da': 'http://www.linguee.hu/magyar-d%C3%A1n',
    'hu-fi': 'http://www.linguee.hu/magyar-finn',
    'hu-el': 'http://www.linguee.hu/magyar-g%C3%B6r%C3%B6g',
    'hu-cs': 'http://www.linguee.hu/magyar-cseh',
    'hu-ro': 'http://www.linguee.hu/magyar-rom%C3%A1n',
    'hu-sk': 'http://www.linguee.hu/magyar-szlov%C3%A1k',
    'hu-bg': 'http://www.bg.linguee.com/%D1%83%D0%BD%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'hu-sl': 'http://www.linguee.hu/magyar-szlov%C3%A9n',
    'hu-lt': 'http://www.linguee.hu/magyar-litv%C3%A1n',
    'hu-lv': 'http://www.linguee.hu/magyar-lett',
    'hu-et': 'http://www.linguee.hu/magyar-%C3%A9szt',
    'hu-mt': 'http://www.linguee.hu/magyar-m%C3%A1ltai',
    'sk-en': 'http://www.sk.linguee.com/slovensk%C3%BD-anglick%C3%BD',
    'sk-de': 'http://www.sk.linguee.com/slovensk%C3%BD-nemeck%C3%BD',
    'sk-fr': 'http://www.sk.linguee.com/slovensk%C3%BD-franc%C3%BAzsky',
    'sk-es': 'http://www.sk.linguee.com/slovensk%C3%BD-%C5%A1panielsky',
    'sk-pt': 'http://www.sk.linguee.com/slovensk%C3%BD-portugalsk%C3%BD',
    'sk-it': 'http://www.sk.linguee.com/slovensk%C3%BD-taliansky',
    'sk-nl': 'http://www.sk.linguee.com/slovensk%C3%BD-holandsk%C3%BD',
    'sk-pl': 'http://www.sk.linguee.com/slovensk%C3%BD-po%C4%BEsk%C3%BD',
    'sk-sv': 'http://www.sk.linguee.com/slovensk%C3%BD-%C5%A1v%C3%A9dsky',
    'sk-da': 'http://www.sk.linguee.com/slovensk%C3%BD-d%C3%A1nsky',
    'sk-fi': 'http://www.sk.linguee.com/slovensk%C3%BD-f%C3%ADnsky',
    'sk-el': 'http://www.sk.linguee.com/slovensk%C3%BD-gr%C3%A9cky',
    'sk-cs': 'http://www.sk.linguee.com/slovensk%C3%BD-%C4%8Desk%C3%BD',
    'sk-ro': 'http://www.sk.linguee.com/slovensk%C3%BD-rumunsk%C3%BD',
    'sk-hu': 'http://www.sk.linguee.com/slovensk%C3%BD-ma%C4%8Farsk%C3%BD',
    'sk-bg': 'http://www.bg.linguee.com/%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%88%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'sk-sl': 'http://www.sk.linguee.com/slovensk%C3%BD-slovinsk%C3%BD',
    'sk-lt': 'http://www.sk.linguee.com/slovensk%C3%BD-litovsk%C3%BD',
    'sk-lv': 'http://www.sk.linguee.com/slovensk%C3%BD-loty%C5%A1sk%C3%BD',
    'sk-et': 'http://www.sk.linguee.com/slovensk%C3%BD-est%C3%B3nsky',
    'sk-mt': 'http://www.sk.linguee.com/slovensk%C3%BD-maltsk%C3%BD',
    'bg-en': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8',
    'bg-de': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BD%D0%B5%D0%BC%D1%81%D0%BA%D0%B8',
    'bg-fr': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%84%D1%80%D0%B5%D0%BD%D1%81%D0%BA%D0%B8',
    'bg-es': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B8%D1%81%D0%BF%D0%B0%D0%BD%D1%81%D0%BA%D0%B8',
    'bg-pt': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BF%D0%BE%D1%80%D1%82%D1%83%D0%B3%D0%B0%D0%BB%D1%81%D0%BA%D0%B8',
    'bg-it': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B8%D1%82%D0%B0%D0%BB%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8',
    'bg-nl': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%85%D0%BE%D0%BB%D0%B0%D0%BD%D0%B4%D1%81%D0%BA%D0%B8',
    'bg-pl': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BB%D0%B0%D0%BA',
    'bg-sv': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%88%D0%B2%D0%B5%D0%B4%D1%81%D0%BA%D0%B8',
    'bg-da': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B4%D0%B0%D1%82%D1%81%D0%BA%D0%B8',
    'bg-fi': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%84%D0%B8%D0%BD%D1%81%D0%BA%D0%B8',
    'bg-el': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B3%D1%80%D1%8A%D1%86%D0%BA%D0%B8',
    'bg-cs': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%87%D0%B5%D1%88%D0%BA%D0%B8',
    'bg-ro': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%80%D1%83%D0%BC%D1%8A%D0%BD%D1%81%D0%BA%D0%B8',
    'bg-hu': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%83%D0%BD%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'bg-sk': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%88%D0%BA%D0%B8',
    'bg-sl': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%81%D0%BB%D0%BE%D0%B2%D0%B5%D0%BD%D1%81%D0%BA%D0%B8',
    'bg-lt': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BB%D0%B8%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D0%B8',
    'bg-lv': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BB%D0%B0%D1%82%D0%B2%D0%B8%D0%B9%D1%81%D0%BA%D0%B8',
    'bg-et': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B5%D1%81%D1%82%D0%BE%D0%BD%D1%81%D0%BA%D0%B8',
    'bg-mt': 'http://www.bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BC%D0%B0%D0%BB%D1%82%D0%B8%D0%B9%D1%81%D0%BA%D0%B8',
    'sl-en': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-angle%C5%A1%C4%8Dina',
    'sl-de': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-nem%C5%A1%C4%8Dina',
    'sl-fr': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-franco%C5%A1%C4%8Dina',
    'sl-es': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-%C5%A1pan%C5%A1%C4%8Dina',
    'sl-pt': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-portugal%C5%A1%C4%8Dina',
    'sl-it': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-italijan%C5%A1%C4%8Dina',
    'sl-nl': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-nizozem%C5%A1%C4%8Dina',
    'sl-pl': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-polj%C5%A1%C4%8Dina',
    'sl-sv': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-%C5%A1ved%C5%A1%C4%8Dina',
    'sl-da': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-dan%C5%A1%C4%8Dina',
    'sl-fi': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-fin%C5%A1%C4%8Dina',
    'sl-el': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-gr%C5%A1%C4%8Dina',
    'sl-cs': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-%C4%8De%C5%A1%C4%8Dina',
    'sl-ro': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-romun%C5%A1%C4%8Dina',
    'sl-hu': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-mad%C5%BEar%C5%A1%C4%8Dina',
    'sl-sk': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-slova%C5%A1%C4%8Dina',
    'sl-bg': 'http://www.bg.linguee.com/%D1%81%D0%BB%D0%BE%D0%B2%D0%B5%D0%BD%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'sl-lt': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-litov%C5%A1%C4%8Dina',
    'sl-lv': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-latvij%C5%A1%C4%8Dina',
    'sl-et': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-eston%C5%A1%C4%8Dina',
    'sl-mt': 'http://www.sl.linguee.com/sloven%C5%A1%C4%8Dina-malte%C5%A1%C4%8Dina',
    'lt-en': 'http://www.lt.linguee.com/lietuvi%C5%B3-angl%C5%B3',
    'lt-de': 'http://www.lt.linguee.com/lietuvi%C5%B3-vokie%C4%8Di%C5%B3',
    'lt-fr': 'http://www.lt.linguee.com/lietuvi%C5%B3-pranc%C5%ABz%C5%B3',
    'lt-es': 'http://www.lt.linguee.com/lietuvi%C5%B3-ispan%C5%B3',
    'lt-pt': 'http://www.lt.linguee.com/lietuvi%C5%B3-portugal%C5%B3',
    'lt-it': 'http://www.lt.linguee.com/lietuvi%C5%B3-ital%C5%B3',
    'lt-nl': 'http://www.lt.linguee.com/lietuvi%C5%B3-oland%C5%B3',
    'lt-pl': 'http://www.lt.linguee.com/lietuvi%C5%B3-lenk%C5%B3',
    'lt-sv': 'http://www.lt.linguee.com/lietuvi%C5%B3-%C5%A1ved%C5%B3',
    'lt-da': 'http://www.lt.linguee.com/lietuvi%C5%B3-dan%C5%B3',
    'lt-fi': 'http://www.lt.linguee.com/lietuvi%C5%B3-suomi%C5%B3',
    'lt-el': 'http://www.lt.linguee.com/lietuvi%C5%B3-graik%C5%B3',
    'lt-cs': 'http://www.lt.linguee.com/lietuvi%C5%B3-%C4%8Dek%C5%B3',
    'lt-ro': 'http://www.lt.linguee.com/lietuvi%C5%B3-rumun%C5%B3',
    'lt-hu': 'http://www.lt.linguee.com/lietuvi%C5%B3-vengr%C5%B3',
    'lt-sk': 'http://www.lt.linguee.com/lietuvi%C5%B3-slovak%C5%B3',
    'lt-bg': 'http://www.bg.linguee.com/%D0%BB%D0%B8%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'lt-sl': 'http://www.lt.linguee.com/lietuvi%C5%B3-slov%C4%97n%C5%B3',
    'lt-lv': 'http://www.lt.linguee.com/lietuvi%C5%B3-latvi%C5%B3',
    'lt-et': 'http://www.lt.linguee.com/lietuvi%C5%B3-est%C5%B3',
    'lt-mt': 'http://www.lt.linguee.com/lietuvi%C5%B3-maltie%C4%8Di%C5%B3',
    'lv-en': 'http://www.lv.linguee.com/latvie%C5%A1u-ang%C4%BCu',
    'lv-de': 'http://www.lv.linguee.com/latvie%C5%A1u-v%C4%81cu',
    'lv-fr': 'http://www.lv.linguee.com/latvie%C5%A1u-fran%C4%8Du',
    'lv-es': 'http://www.lv.linguee.com/latvie%C5%A1u-sp%C4%81%C5%86u',
    'lv-pt': 'http://www.lv.linguee.com/latvie%C5%A1u-portug%C4%81%C4%BCu',
    'lv-it': 'http://www.lv.linguee.com/latvie%C5%A1u-it%C4%81%C4%BCu',
    'lv-nl': 'http://www.lv.linguee.com/latvie%C5%A1u-holandie%C5%A1u',
    'lv-pl': 'http://www.lv.linguee.com/latvie%C5%A1u-po%C4%BCu',
    'lv-sv': 'http://www.lv.linguee.com/latvie%C5%A1u-zviedru',
    'lv-da': 'http://www.lv.linguee.com/latvie%C5%A1u-d%C4%81%C5%86u',
    'lv-fi': 'http://www.lv.linguee.com/latvie%C5%A1u-somu',
    'lv-el': 'http://www.lv.linguee.com/latvie%C5%A1u-grie%C4%B7u',
    'lv-cs': 'http://www.lv.linguee.com/latvie%C5%A1u-%C4%8Dehu',
    'lv-ro': 'http://www.lv.linguee.com/latvie%C5%A1u-rum%C4%81%C5%86u',
    'lv-hu': 'http://www.lv.linguee.com/latvie%C5%A1u-ung%C4%81ru',
    'lv-sk': 'http://www.lv.linguee.com/latvie%C5%A1u-slov%C4%81ku',
    'lv-bg': 'http://www.bg.linguee.com/%D0%BB%D0%B0%D1%82%D0%B2%D0%B8%D0%B9%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'lv-sl': 'http://www.lv.linguee.com/latvie%C5%A1u-slov%C4%93%C5%86u',
    'lv-lt': 'http://www.lv.linguee.com/latvie%C5%A1u-lietuvie%C5%A1u',
    'lv-et': 'http://www.lv.linguee.com/latvie%C5%A1u-igau%C5%86u',
    'lv-mt': 'http://www.lv.linguee.com/latvie%C5%A1u-maltie%C5%A1u',
    'et-en': 'http://www.et.linguee.com/eesti-inglise',
    'et-de': 'http://www.et.linguee.com/eesti-saksa',
    'et-fr': 'http://www.et.linguee.com/eesti-prantsuse',
    'et-es': 'http://www.et.linguee.com/eesti-hispaania',
    'et-pt': 'http://www.et.linguee.com/eesti-portugali',
    'et-it': 'http://www.et.linguee.com/eesti-itaalia',
    'et-nl': 'http://www.et.linguee.com/eesti-hollandi',
    'et-pl': 'http://www.et.linguee.com/eesti-poola',
    'et-sv': 'http://www.et.linguee.com/eesti-rootsi',
    'et-da': 'http://www.et.linguee.com/eesti-taani',
    'et-fi': 'http://www.et.linguee.com/eesti-soome',
    'et-el': 'http://www.et.linguee.com/eesti-kreeka',
    'et-cs': 'http://www.et.linguee.com/eesti-t%C5%A1ehhi',
    'et-ro': 'http://www.et.linguee.com/eesti-rumeenia',
    'et-hu': 'http://www.et.linguee.com/eesti-ungari',
    'et-sk': 'http://www.et.linguee.com/eesti-slovaki',
    'et-bg': 'http://www.bg.linguee.com/%D0%B5%D1%81%D1%82%D0%BE%D0%BD%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'et-sl': 'http://www.et.linguee.com/eesti-sloveeni',
    'et-lt': 'http://www.et.linguee.com/eesti-leedu',
    'et-lv': 'http://www.et.linguee.com/eesti-l%C3%A4ti',
    'et-mt': 'http://www.et.linguee.com/eesti-malta',
    'mt-en': 'http://www.mt.linguee.com/malti-ingli%C5%BC',
    'mt-de': 'http://www.mt.linguee.com/malti-%C4%A1ermani%C5%BC',
    'mt-fr': 'http://www.mt.linguee.com/malti-fran%C4%8Bi%C5%BC',
    'mt-es': 'http://www.mt.linguee.com/malti-spanjol',
    'mt-pt': 'http://www.mt.linguee.com/malti-portugi%C5%BC+',
    'mt-it': 'http://www.mt.linguee.com/malti-taljan',
    'mt-nl': 'http://www.mt.linguee.com/malti-olandi%C5%BC',
    'mt-pl': 'http://www.mt.linguee.com/malti-pollakk',
    'mt-sv': 'http://www.mt.linguee.com/malti-svedi%C5%BC',
    'mt-da': 'http://www.mt.linguee.com/malti-dani%C5%BC+',
    'mt-fi': 'http://www.mt.linguee.com/malti-finlandi%C5%BC+',
    'mt-el': 'http://www.mt.linguee.com/malti-grieg',
    'mt-cs': 'http://www.mt.linguee.com/malti-%C4%8Bek',
    'mt-ro': 'http://www.mt.linguee.com/malti-rumen',
    'mt-hu': 'http://www.mt.linguee.com/malti-ungeri%C5%BC',
    'mt-sk': 'http://www.mt.linguee.com/malti-slovakk',
    'mt-bg': 'http://www.bg.linguee.com/%D0%BC%D0%B0%D0%BB%D1%82%D0%B8%D0%B9%D1%81%D0%BA%D0%B8-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8',
    'mt-sl': 'http://www.mt.linguee.com/malti-sloven',
    'mt-lt': 'http://www.mt.linguee.com/malti-litwan',
    'mt-lv': 'http://www.mt.linguee.com/malti-latvjan',
    'mt-et': 'http://www.mt.linguee.com/malti-estonjan'
  };

  var base = languagePairUrl[fromCode + "-" + toCode];
  if (!base) {
    return null;
  }

  var item = [];
  item[1] = fromCode;

  if (item[1]=='de')
    theOptionValue='german';
  else if (item[1]=='en' || item[1]=='us' || item[1]=='gb')
    theOptionValue='english';
  else if (item[1]=='fr')
    theOptionValue='french';
  else if (item[1]=='pt' || item[1]=='br')
    theOptionValue='portuguese';
  else if (item[1]=='es' || item[1]=='pe' || item[1]=='co' || item[1]=='ar' || item[1]=='cl')
    theOptionValue='spanish';
  else if (item[1]=='it')
    theOptionValue='italian';
  else if (item[1]=='nl')
    theOptionValue='dutch';
  else if (item[1]=='pl')
    theOptionValue='polish';
  else if (item[1]=='sv' || item[1]=='se')
    theOptionValue='swedish';
  else if (item[1]=='da' || item[1]=='dk')
    theOptionValue='danish';
  else if (item[1]=='fi')
    theOptionValue='finnish';
  else if (item[1]=='el' || item[1]=='gr')
    theOptionValue='greek';
  else if (item[1]=='cs' || item[1]=='cz')
    theOptionValue='czech';
  else if (item[1]=='ro')
    theOptionValue='romanian';
  else if (item[1]=='hu')
    theOptionValue='hungarian';
  else if (item[1]=='sk')
    theOptionValue='slovak';
  else if (item[1]=='bg')
    theOptionValue='bulgarian';
  else if (item[1]=='sl' || item[1]=='si')
    theOptionValue='slovene';
  else if (item[1]=='lt')
    theOptionValue='lithuanian';
  else if (item[1]=='lv')
    theOptionValue='latvian';
  else if (item[1]=='et' || item[1]=='ee')
    theOptionValue='estonian';
  else if (item[1]=='mt')
    theOptionValue='maltese';
  else
    theOptionValue='auto';

  // taken verbatim from http://static.linguee.com/15483/javascript/linguee.js.g
  var urlencode = function(str) {
      return escape(str).replace(/\+/g,'%2B').replace(/%20/g, '+').replace(/\*/g, '%2A').replace(/\//g, '%2F').replace(/@/g, '%40');
  }
  // query = encodeURIComponent(query);
  // query = query.replace(/%20/g, '+');
  query = urlencode(query);
  return base +"?query=" + query + "&source=" + theOptionValue;
}
